"""
Django settings for trademarket_django project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kpx6u$@6q$#eeet8170v(1s9v-1z!&l^wdhfh$tftk=&2*numg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'user.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'oauth2_provider',
    'corsheaders',
    'user.apps.UserConfig',
    'stuff.apps.StuffConfig',
    'rest_framework',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trademarket_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trademarket_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'trademarket',
        'USER':'root',
        'PASSWORD': 'ekdhf1221!',
        'HOST': 'trademarket.c8yqzix4ytsf.us-east-1.rds.amazonaws.com',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

AWS_ACCESS_KEY_ID = 'ASIAWOXSBMPQY3I5KW4M'
AWS_SECRET_ACCESS_KEY = 'KhvTyZLfRVus03HuCvr3XBrtFDiE+5245zI/u3iZ'
AWS_SESSION_TOKEN = 'FQoGZXIvYXdzEFoaDEDRd3etAwYRT1lwgCKBAtGXvzRxd0JtQ4ZSImAPM1h4CtFupsbUeXnrCIQswpQwnKTGlwV7He7YLfyac0BM+/TJUFsNKNIdnFXi9u2QlcLc/9BP3TG7+BWfddoqwtuDBva6PMNOh2/eZVbNpEKr8VI5rsH2vygo+NEgCiVAQ82KJ+rUxMF29HIG6Z0iHGNgVQHuyZMV8tyf8w1gwP7glfNIq7FBUdEXfPQuW3iXkUWalSc4MwXHLFDdXuvSpBPj6G5jDUb4lsJjJbspr+eUKNm2RDIMhsgXjLSg/SLK8fQPH4D9Ye++JYYAsYtupi+4megi0Fl+YQYhXDrJjsUqXd8vkO+rA7NXbr7Xn1KmhPoTKObi/OoF'

AWS_STORAGE_BUCKET_NAME = 'cdn.trademarket'
AWS_S3_CUSTOM_DOMAIN = 'd1j5f7lvpy2uwt.cloudfront.net'
AWS_S3_URL = 'https://%s/' % AWS_S3_CUSTOM_DOMAIN
AWS_S3_SIGNATURE_VERSION = 's3v4'

STATIC_URL = '/static/'
STATIC_ROOT = 'static/'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# MEDIA_ROOT = '/media/'
# MEDIA_URL = '/media/'

AWS_LOCATION = 'assets/'
ASSET_URL = '%s%s' % (AWS_S3_URL, AWS_LOCATION)
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'trademarket_django.storages.FileStorage'




CORS_ORIGIN_ALLOW_ALL = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',

    )
}

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
}
