# Generated by Django 2.2.4 on 2019-08-13 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('stuff', '0003_stuff_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.Stuff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuffs', to='user.User')),
            ],
        ),
    ]
