# Generated by Django 2.2.4 on 2019-08-19 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_userstuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuffs', to='stuff.Category'),
        ),
    ]
