# Generated by Django 2.2.3 on 2019-08-23 02:29

from django.db import migrations, models
import stuff.models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_auto_20190819_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=models.ImageField(null=True, upload_to=stuff.models.get_stuff_image_path),
        ),
    ]
